project:
  type: website
  output-dir: docs

website:
  title: |
    Martin Søyland
  favicon: favicon.ico
  page-navigation: true
  navbar: 
    search: true
    left:
      - publications.qmd
      - conference.qmd
      - teaching.qmd
      - data.qmd
      - R.qmd
      - blog.qmd

format:
  html:
    theme:
      dark: [darkly, style.scss]
      light: [flatly, style.scss]
    toc: true
    mainfont: expressway
    monofont: expressway