---
title: "Publications"
---

2022:

- [Party Control and Responsiveness: How MPs Use Variation in Lower-Level Institutional Design as an Electoral Responsiveness Mechanism (Forthcoming)](http://ceur-ws.org/Vol-3133/paper07.pdf)

2021:

- [Committee-Membership Matters, Party Loyalty Decides in <em>The Politics of Legislative Debates (Hanna Back, Marc Debus, and Jorge M. Fernandes)</em> (Collaberation with Bjørn Høyland)](https://oxford.universitypressscholarship.com/view/10.1093/oso/9780198849063.001.0001/oso-9780198849063-chapter-31)
- [Climate politics in har times: How local economic shocks influence MPs attention to climate change (Collaberation with Henning Finseraas and Bjørn Høyland)](https://ejpr.onlinelibrary.wiley.com/doi/full/10.1111/1475-6765.12415)

2019:

- [Is all PR good PR? How the content of media exposure affects candidate popularity (Collaberation with Haakon Gjerløw and Peter Egge Langsæther)](https://www.sciencedirect.com/science/article/pii/S0261379418303548)<br><br>
- [Electoral Reform and Parliamentary Debates (Collabeartion  with Bjørn Høyland)](https://onlinelibrary.wiley.com/doi/full/10.1111/lsq.12237)

2018:

- [The Talk of Norway: a richly annotated corpus of the Norwegian parliament, 1998–2016. (Collaberation with Emanuele Lapponi, Erik Velldal, and Stephan Oepen)](https://link.springer.com/article/10.1007/s10579-018-9411-5)

2017:

- [Survival of the Ministers: On Ministerial Durability in Postwar Norway (2017)](http://onlinelibrary.wiley.com/doi/10.1111/1467-9477.12086/abstract)

2015:

- [Tilbakeholden og ekspansiv liberalisme: - Om utenrikspolitikk i State of the Union-taler (2015)](https://www.idunn.no/ip/2015/01/tilbakeholden_og_ekspansiv_liberalisme_-_om_utenrikspoliti)
