---
title: "Person eller parti?"
author: "Martin Søyland"
date: "2024-04-09"
categories:
  - valgordning
  - personstemmer
  - norsk politikk
---

I det nyaste tilskotet i serien [“Sanna Sarromaa har ei meining”](https://www.vg.no/nyheter/meninger/i/P4W46p/de-intetsigendes-demokrati) kritiserast det norske valsystemet for mangel på valfridom. Me må sjå til Finland, sjølvsagt. Innlegget har rett i at det norske valsystemet gjer mykje makt til partia og at erfaring og posisjon er viktig for nominasjon innad i desse partia. Men drøftinga rundt kva dette inneber, står til stryk. La meg svara i ein liknande tone.

For å ta det mest graverande først, så antydar Sarromaa at lukka lister ved val er eit eksklusjonskriterie for å vera demokrati. Det finst ikkje seriøse definisjonar av demokrati som brukar dette kriteriet. Sarromaa referer til den finske presidenten, som skal har sagt til ho at Noreg ikkje er eit demokrati. Sjølv om Stubb er statsviter, er han ikkje ein stor demokratiforskar, såvidt eg veit. Val handlar om å delegera makt. Korleis denne delegeringa tek form, varierar stort mellom valsystem. Og fleire demokrati har lukka partilister. Om me skal ta argumenta til Sarromaa på alvor, må me innføra
[potteskårdemokrati](https://snl.no/ostrakisme).

Sarromaa skriv vidare at mangel på veljarinnverknad førar til politikarar med mindre kompetanse og handlekraft. Empirien ho lenar seg på er nokre anekdotar frå Gjøvik og Lillehammer. Det er her det gjekk
opp for meg kvifor me må bruka så mykje ressursar på å læra kjeldekritikk og referanseføring til studenter som kjem rett frå videregåande.

Hvis me skal vera litt meir alvorlege, er det både fordelar og ulemper av opne og lukka lister i val og det er ganske mykje forskning å lena seg på. Her skil me ofte mellom partisentrerte og kandidatsentrerte valsystem, der opne og lukka lister bare er ein av fleire aspekt som trekk systemet i den eine eller andre retninga. Det er, til dømes, lettare å koordinera politikk i partisentrerte system fordi me delegerar makt til partia sine politiske platformar og partia forhandlar om politikk basert på desse. Når systemet er meir kandidatsentrert, vert det, blant anna, lettare for politikarane å representera valkrinsen sin. Óg er jo sjølvsagt meir komplekst i røynda; dette er idealtypar. Til dømes, er det mykje individuell lokal representasjon og tilpasning i forskjellige arenaer på Stortinget, på trass av det partisentrerte systemet til Noreg ([Finseraas et. al 2021](https://ejpr.onlinelibrary.wiley.com/doi/full/10.1111/1475-6765.12415)).

I den ganske store litteraturen som forskar på effektane av valsystem på aktørane i systemet, kan me blant anna sjå til [Cirone, Cox og Fiva (2020)](https://doi.org/10.1017/S0003055420000416). Dei har forska på nominasjon og politiske karrierer i Noreg frå 1945-2019. Veldig forenkla, finn dei to gjennomgåande praksisar: nominasjon av sittande politikarar og interne opprykk basert på erfaring. Dei peiker blant anna på at senoritetssystem kan gje meir stabile og disiplinerte parti. Noko som gjer val meir oversiktlege for veljarane.

Dette er ein viktig debatt å ta. Men me kjem ikkje nokon veg med halvdårlege hofteskudd frå Finland. Om me skal fortsetja å gje så mykje makt til dei politiske partia som me gjer, må me óg ha mykje strengare ansvarleggjeringsmekanismar på plass for partia og deira medlemmar. Me treng ikkje sjå lenger enn alle dei politiske skandalane dei siste åra for å forstå at me treng meir anvarleggjering. Og, det er eit reelt alternativ å gje velgarane meir makt via opne(re) lister. Det største problemet er at aktørane som kan endra på systemet -- politikarane sjølv -- då (sannsynligvis) sett seg sjølv i ein svakere posisjon for gjenval enn i systemet me har no. Det vert som å la tjuven bestemma låsen på fengselsdøra.