---
title: "Plagsomt med demokrati i Time kommune"
description: "[Leserinnlegg i Jærbladet](https://www.jbl.no/jeg-er-dypt-uenig-i-verdiene-vollsund-fremmer-men-jeg-har-respekt-for-at-han-torr-a-si-akkurat-dette/o/5-103-641851)"
author: "Martin Søyland"
date: "2021-06-21"
categories:
  - norsk politikk
  - demokrati
  - lokal politikk
---

Det er med stor interesse jeg, som har vokst opp og levd over halve livet mitt på Frøyland i Time, har fulgt med på debatten om etablering av datasenter på Kalberg/Kverneland. Jeg tror denne saken er ekstremt viktig for demokratiet i Time kommune; et demokrati som har ligget i dvale over flere tiår. Saken setter lys på viktige demokratiske prinsipper, som transparente prosesser, hvordan politikere skal forholde seg til informasjon fra fagpersoner og hva det egentlig innebærer å lytte til en befolkning. 

[Prosessen.]{.cream}
Hvis befolkningen skal vise tillitt til politikere, må saksgang være transparent. Det er også lovpålagt (offentlighetsloven) å ha transparens i demokratiske institusjoner. I saken om datasenteretablering på Kalberg/Kverneland er saksgangen til tider et mysterium. Hvordan kan ingen i kommunestyre ha visst om planene før valget 2019 (ref Andreas Vollsund i møtet på Brekkenuten 10.06.2021), [når Aftenposten visste det allerede mars 2018](https://www.aftenbladet.no/lokalt/i/A2QO2r/disse-stedene-i-rogaland-kan-google-co-snart-bygge-datasenter)? Hvorfor hadde kommunen ingen dokumentasjon på saken da MASIV reiste rundt til grunneiere med opsjonsavtaler i slutten av 2019? Hvor var kommunens initiativ til å opplyse befolkningen om et prosjekt av dette kaliberet i en tidlig fase? Det har dukket opp mange spørsmål som dette hos flere av de berørte i saken over hele prosessen.

Så, [når Kjell Olav Stangeland klager seg over at “konspirasjonsteorier” har dukket opp](https://www.jbl.no/kraftige-ord-i-kommunestyret-sjeler-selger-seg-som-skjoger/s/5-103-639796), kan han gjerne se seg selv i speilet og spørre om han har prøvd å vende steiner i prosessen? Har han forsikret seg om at administrasjonen har fulgt de reglene de skal? Har han spurt seg hvilke aktører og interesser som har makt og innflytelse? Hvor sikker er han på at dette er den rette løsningen for innbyggerne på Kalberg, Kvernaland og Frøyland? Ingen andre enn kommunestyret og administrasjonen i Time vet svaret på disse spørsmålene, fordi hver gang noen spør blir de møtt med svar som kritiserer at det blir spurt om i utgangspunktet — at det er et angrep mot den enkeltes integritet. Det kan ikke kalles en konspirasjonsteori før dere er åpne om prosessen fra start til slutt. Jeg hadde heller ikke blitt veldig overrasket om en grundig, uavhengig, revisjon hadde funnet brudd på god saksgang i denne saken.

[Kunnskap.]{.cream}

Det var også forbausende å se [kommunestyremøtet 15.06.2021](https://time.kommunetv.no/archive/139) og forholdet man har til uttalelser fra fagfolk. Igjen glimter Kjell Olav Stangeland til. På tross av diverse konsekvensutredninger og uttalelser fra fagfolk, hvor det kommer frem at konsekvensene for natur og biomangfold er ganske store og kritiske — for eksempel for den ikoniske vipa — mener Stangeland at utbyggingen ikke vil ha så store konsekvenser for vipebestanden på Jæren. Dette har Stangeland ingen belegg for å mene. Da har jeg mer sansen for å stå for det man mener, som Andreas Vollsund gjorde ved folkemøtet på Brekkenuten da han sa at han er villig til å ofre natur, biomangfold og turområder for de potensielle arbeidsplassene planene vil generere. Jeg er dypt uenig i verdiene Vollsund fremmer, men jeg har respekt for at han tårer å si akkurat dette.

Men Vollsund synder dessverre også i å behandle kunnskap på en verdig måte når han på Dagsrevyen sier: “[...] her kan vi skape flere tusen arbeidsplasser, eller hvertfall tusen. Det er det jeg alltid har sagt.” Også her er både konsekvensutredning og fagpersoner veldig tydelige på at arbeidsplasstallene er veldig usikre av flere grunner. Kort sagt, er det vanskelig å fastsette gode tall på hvor mange arbeidsplass planene vil generere både fordi “spillover”-effektene av prosjektet er vanskelig å forutse, og fordi de eneste dataene vi har på arbeidsplasser, er produsert av aktører som har store egeninteresser i å få utbyggingen gjennom. Det eneste vi vet med sikkerhet, er at arbeidsplassene som er generert ved liknende prosjekter er vesentlig lavere enn det politikerne i Time kommune har blitt forespeilet. Uttalelsen til ordføreren er i beste fall et misvisende bilde på hvor sikre disse tallene er. I verste fall er de misledende med overlegg.  

[Å bli hørt.]{.cream}
Et stort tema på det nevnte folkemøtet på Brekkenuten var det filosofiske spørsmålet “hva betyr det å bli hørt?” Her er det også totalt mageplask fra politikerne i Time kommune. Flere mener at de “har hørt på hva motstanderne av planene sier, men at er ikke enig — og det må være lov”. Det er selvfølgelig lov å være uenig. Men sett i kontekst av fraværende vilje til å ta inn over seg argumentene fra fagpersoner og utredninger, samtidig som man vekter usikre tall alt for høyt og møter de fleste motargumenter med versjoner av “men alle arbeidsplassene da?”, er det fristende å si at det disse politikerene karakteriserer som å høre etter, egentlig er å la informasjon gå inn det ene øret og ut det andre. Det er forskjell på å høre og “hørra itte”.

Politikere og administrasjon i Time kommune har latt seg forføre av store planene om datasenter på Kalberg/Kverneland. Prosessen har vært så lukket som overhodet mulig, helt til presset fra privatpersoner har krevd mer åpenhet. De negative konsekvensene er ikke like viktige som arbeidsplasser. Ikke denne gang. Ikke forrige gang. Og sannsynligvis ikke neste gang. Slik rives landbruk, biomangfold, turområder, natur og gode vennskap fra hverandre på Jæren — bit for bit.

Og nei, Andreas Vollsund, jeg er ikke engasjert av Vern Kvernaland til å skrive dette. Det engasjementet har du og dine kollegaer gitt meg helt på egenhånd.
