---
title: "Tur"
author: "Martin Søyland"
date: "2023-12-01"
categories:
  - lokalpolitikk
  - time kommune
  - norsk politikk
---

Å planlegga ein tur kan vera vanskeleg. Ikkje berre må me passa på at me har med oss alt me
treng – tannbørste, undertøy, regnklede, telefon, det er mykje me må hugsa på – me må også
passa på at me har godt og høveleg selskap med oss. Nokre gonger vil me helst vere åleine,
nokre gonger med familie, nokre gonger med vener, nokre gonger med kollegaer. Alle, kanskje
utanom å vere åleine, har fellesnemnaren at me helst reiser saman med folk me likar. Om du
reiser med nokon du ikkje likar, då kan jo reisa verta plagsam og kjip. Trøytande.

Derfor støttar eg personleg at formannskapet i Time kommune var selektive med reisefølge då
dei [reiste til Hamar for å sjå på TikTok-datasenteret](https://www.jbl.no/politikerne-drar-pa-tiktok-turn-til-hedmarken-her-er-programmet/s/5-103-983124). Dei har jo planar om å byggje eit større
datasenter sjølv. Mange arbeidsplassar står på spel. Då kan ikkje kven som helst bli med på
tur.

Faktisk, når eg tenkte på dette, er det litt dumt at det ofte finst folk i eit formannskap som
fleirtalet ikkje likar. Det er mest for gale at to, tre, fire personer skal få lov å vera med på tur
når ingen likar dei. I tillegg har dei stilt spørsmål. Dei lurte på kvifor næringslivtoppane fekk
vera med. Klart dei skal vera med. Det er jo dei som har greie på dette.

Her har altså fleire veldig viktige personar organisert og stelt i stand ein tur for å sjå på noko
jilt. Lærerik substans. Det er mykje arbeid å organisera tur. Så kjem frekkasane og foreslår
at gode folk skal bli ekskludert. Berre fordi plagsame meiningsmotstandarar ikkje har vorte
invitert. Det er ikkje plass til alle. Takka seg te.

Eg syns at berre dei som verkeleg ville sett pris på turen burde fått vera med. Faktisk har forskning vist at [kvinner er meir tilbøyelege til å vera bekymra for miljø og natur](https://www.theguardian.com/environment/2020/feb/06/eco-gender-gap-why-saving-planet-seen-womens-work). Dei
er òg mykje mindre glade i næringsliv. Yngre òg. Dei verdsett det ikkje. Dei burde ikkje fått
vera med på turen. Kvinner og yngre. Spesielt ikkje yngre kvinner.

Det same gjeld dei som er til venstre. Dei kan ikkje verdsetja det som vert skapa der borte på
austlandet. Dei kjem til å stilla vanskelege spørsmål om naturvern, matproduksjon, straum
og det som verre er. Nei. Alle som er til venstre for midten burde ikkje fått vera med.

Dei eldre lener seg òg ofte mykje meir mot ting som nostalgi og konservative haldningar. Dei
likar ikkje endring. Dei likar å verna. Men for å få til utvikling må me jo ha endring. Det er
jo eit sentralt prinsipp i korleis verda fungerar. Utan vekst døyr me, alle saman! Til helvete 
med maten! Me treng vekst. Dei som er eldre enn 60 skulle aldri fått vera med på turen. Dei
kan verta alt for sentimentale i møte med endring. Dei gjorde nok turen utriveleg for resten.

Det heiter tross alt forMANNskap. Få sendt ei samling kvite menn mellom 40 og 60 år til
høgre i politikken. Det vert ei mykje meir komfortabel reise for alle. Det er òg, tilfeldigvis, den
gruppa som har mest greie på dette. Næring, arbeidsplassar, vekst og pengar. Andre forstår
ikkje. Dei har ikkje lyst forstå. Nei, meiningsmotstand og demokrati gjer det vanskeleg å få
til ting i dette landet.